#!/bin/sh
opkg update 2>/dev/null || apt update 2>/dev/null || apk update 2>/dev/null
opkg install bash 2>/dev/null || apt install bash 2>/dev/null || apk install bash 2>/dev/null
mkdir -p /opt
curl -sSL -o /opt/z4r_boot "https://raw.githubusercontent.com/Koviand/z4r/main/z4r" || exit 1
chmod +x /opt/z4r_boot
Z4R_AUTO=1 exec /opt/z4r_boot
